### ISSUE TITLE
Add quarks to the list of gen particles

### ISSUE THREAD

**Issue by yiiyama** [MiT-HEP/NeroProducer#117]
We need to figure out quarks of which status flags should be used.

**Comment by amarini** [comment]
And neutrinos.

**Comment by yiiyama** [comment]
We should also add BSM particles - it seems that so far we've been using 1000022 (lightest neutralino) for our dark matter particles so probably that's enough for now.

**Comment by amarini** [comment]
This is done for miniaod.
