### ISSUE TITLE
AOD

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#12]
We need a miniAOD production on the fly from AOD.

**Comment by drkovalskyi** [comment]
There should be some fairly trivial instructions how to run miniAOD yourself. I suspect cmsDriver or matrix or something of this sort should work. Just need to find instructions and integrate it.

We need to make sure it's functional. It's very likely that sometimes we may just need to run a new version of miniAOD on top of AOD.

**Comment by zdemirag** [comment]
There are these instructions on: https://twiki.cern.ch/twiki/bin/view/CMS/MiniAOD
cmsDriver.py miniAOD -s PAT [ --data | --mc [ --fast ] ]  --eventcontent [ MINIAOD | MINIAODSIM ] --runUnscheduled --filein xxx  --conditions yyy --no_exec
Could this help?
Zeynep

**Comment by drkovalskyi** [comment]
Yes, this is the right information. Now we need to find a way to integrate whatever cmsDriver produces as python config into our framework so that we can run both.
