### ISSUE TITLE
JEC

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#122]
* V5 for 50ns
* V2 for 25ns

**Comment by zdemirag** [comment]
It turns out that JEC is wrong in the 2015D Prompt Miniaod:
https://indico.cern.ch/event/445928/attachments/1160241/1670296/METDatavsMC_2015D_250915.pdf
Use of type1 met is not recommended for miniaod unless it is recalculated with the proper JEC. (raw met gives better agreement out of the box)

**Comment by amarini** [comment]
I tried to do it by myself and the one done in miniAOD and the result is the same. (at least for jets).

**Comment by amarini** [comment]
In anycase, I'm going to try the production I did last days:
/store/user/amarini/Nero/v1.1
