### ISSUE TITLE
Trigger object matching

### ISSUE THREAD

**Issue by yiiyama** [MiT-HEP/NeroProducer#124]
The way we limit the offline collection to match to trigger objects is not safe against HLT filters not properly assigning the TriggerObject type.
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroTrigger.cpp#L88

For example, Zeynep and I just found that HLTEgammaGenericFilter, which is the last filter (with saveTags) of an single electron path, saves the trigger objects as TriggerPhoton:
https://github.com/cms-cvs-history/HLTrigger-Egamma/blob/master/src/HLTEgammaGenericFilter.cc#L64
So we won't match the single electron objects to offline leptons in the current implementation.

I'd say we should just get rid of the restriction on the trigger object type.

**Comment by amarini** [comment]
In that case you may also match to muons,  that doesn't sound very good. For the moment we are not using any particular trigger matching... so no problem. 
Probably I will merge the EGAMMA but for the others there maybe some concerns (like jet with e mu, tau with e Mu ...).
What do you think?
