### ISSUE TITLE
Fatjet new variable

### ISSUE THREAD

**Issue by yiiyama** [MiT-HEP/NeroProducer#132]
My bad, merged a change to BareFatJets without discussing with everyone first. It added one new discriminator (vector<float>). Now that the FatJet class is getting fatter, perhaps we should employ the extension flag here as well?

**Comment by amarini** [comment]
Yes, that is likely to be used. Discuss with @jsalfeld what it is interested in having in the fatjets.
We may be interest in an unprecise future to the top-tagger too (for a tb analysis), but we will see.

**Comment by zdemirag** [comment]
@sidnarayanan

**Comment by yiiyama** [comment]
I suppose we can close this 4-month old issue.
