### ISSUE TITLE
mjId2015 doesn't seem to be filled in jet selection from MiniAOD

### ISSUE THREAD

**Issue by dabercro** [MiT-HEP/NeroProducer#173]
In particular, jetSelBits [iJet] & 1024 == 1024 always seems to return 0 for the leading jet.
This is from the Nero from MiniAOD v1.2 in Andrea's EOS.

**Comment by amarini** [comment]
You need to check the id selection and implement it here:
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroJets.cpp#L196
and fill the selbits here:
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroJets.cpp#L137

@zdemirag 
you may want also to clean the logic for "monojet" and "monojetloose" that are called here:
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroJets.cpp#L177
and ovrewritten here:
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroJets.cpp#L192

**Comment by dabercro** [comment]
Added the lines and made pull request.
