### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#194]
Either the reclustering or puppi are too slow to produce without skimming.
(about a factor 60x) 
I'm producing with this branch at the moment:
https://github.com/amarini/NeroProducer/tree/topic_nofat

**Comment by amarini** [comment]
Some time info:
Nero standalone take something like 5s/1000events.
With only the puppiSequence takes 2m/1000events.
With also the fatjetSequence takes 5m/1000events.

**Comment by drkovalskyi** [comment]
I think we just need a clear flag to enable/disable heavy code such like puppi or jet reclustering. I think we should keep it enabled by default, but when it's needed or it should be trivial to disable the code. I have discussed the issue with Sid and he promised to implement such a flag (or a few)
