### ISSUE TITLE
GenParticles

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#209]
Gen particles needs to be reviewed.

For the moment they are very big.

In the DY they were still sort of fine:
https://amarini.web.cern.ch/amarini/NeroProducer/2e63c85a8a9420797558855ccbc9950f3d1548a6/size.png

But in the ttbar samples become huge:
![nerosize](https://cloud.githubusercontent.com/assets/4516989/15422533/58b1e20c-1e79-11e6-80f9-b48bddc84390.png)

**Comment by sidnarayanan** [comment]
I took a quick look into this. If I look at a ttbar event, I see 10 copies of each top saved, and similarly many copies of all the decay particles. We can probably only save particles of a particular status, unless someone needs all these intermediate particles.

**Comment by amarini** [comment]
These are part of the pythia showering. We don't need all the shower.
Probably the easiest thing to do is to check that the mother has not the same pdgId for all the gen particles we save.
