### ISSUE TITLE
Few issues / suggestions in 8_0_10

### ISSUE THREAD

**Issue by zdemirag** [MiT-HEP/NeroProducer#235]
Few notes for 8_0_10:

1. For the smeared Jets, it is currently over-writing the JEC only jets. I would prefer if there is an other p4 for the smeared jets. Because not all analysis use smeared jets for central values.

2. If an analysis is using smeared jets, than this has to be also propagated into MET.

3. Some new met filters will be needed in MC too so moving the isData flag is better for the MET Filters. 
    * For the data we need to switch to a new met filter handle (PAT)

4. In 8_0_10 Event Num, RunNum, LumiNum is always 0 , -1 (i.e. it is not filing it correctly) only for the events tree (all tree is filled correctly). 

5. For Photon eta (similarly Electron eta) I would prefer to save the super cluster eta. If there is no objection we can change that centrally.

6. For pruned mass, we currently save the raw value, we should also save (or update the raw value with) L2L3 corrected value (POG recommended usage). Either solution is fine, I am just looking for feedback in case people prefer one or the other.

**Comment by amarini** [comment]
For point 4) #230 and #229 fix

**Comment by amarini** [comment]
for point 5) do you mean as an extra variable or as eta ? 
If as eta for electron is wrong, because you need to subtract the vertex position, but still may be useful for detector related studies/scale factors ...

**Comment by amarini** [comment]
point 6. up to you, if somebody implements (I guess @sidnarayanan )

**Comment by amarini** [comment]
point 1. We already save the un-smeared values as read by the nero producer:
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroJets.cpp#L128-L129

**Comment by zdemirag** [comment]
Point 5) I was thinking about replacing the p4 eta with the super cluster eta.
Point 6) i have the implementations to make the relevant PRs. But it is more of a question for the other users of pruned mass. (also some other mass variables are no longer available in 80x)
Point1 ) This is not the same thing, this is the reference pt which doesn't necessarily has the latest/greatest JEC

**Comment by amarini** [comment]
point 2-3. your territory, you give recommendation.

**Comment by amarini** [comment]
5. is probably not what you want to do. The supercluster eta is the position inside the detector with respect to the fixed center of the detector. You want the 4 momentum computed against the primary vertex, and so the "z" of the primary vertex needs to be "subtracted".

**Comment by amarini** [comment]
Point 6. JEC are updated prior to the neroproducer analyzer, therefore nero will see only jes corrected jets.

**Comment by zdemirag** [comment]
Few follow up. 

I think it is actually the SCeta recommended for photons as Id etc variables are calculated with the SCeta
Also the some of the random fillers are also seems to be not working. Like various MET flavors (even with the extended mode enabled.) Seems to be a similar problem to the eventNum/ runNum/ aluminum filler problem.  Not sure how / when this broke.

**Comment by amarini** [comment]
Can we meet to discuss this later today ? (@drkovalskyi may also want to join)

**Comment by zdemirag** [comment]
we practically address all the comments here closing the issue
