### ISSUE TITLE
Trigger Limitation to 32

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#259]
The trigger limitation to 32 is due **ONLY** in the trigger Matching. 
The code should not crash if you have 100000 triggers, 
but the matching will not work for the 33rd trigger on.
(**triggerFired will be filled correctly**)

https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroTrigger.cpp#L36

We can move to 64 changing these lines to uint64_t (and the corresponding tree, l : a 64 bit unsigned integer (ULong64_t) ) 
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/interface/BareTrigger.hpp#L28-L31
uint128 are supported by c++ but not by root. for more than 64, we need to change the tree structure, to vector< vector<int> > or to vector< myclass>.

If you don't plan to use it, privilege the first 32 triggers for the ones that may be suitable for matching.
You may want to plan to do so reduce the matching to the first 32 triggers:

https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroTrigger.cpp#L130

maybe the easiest thing is to have a parameter to have the first X triggers to be match and the other will be provided only as an event trigger, with the benefit of fasting up the all code ... I guess that these are < 10.

**Comment by zdemirag** [comment]
Given trigger matching is relatively slow, it would make it even more slow to make any all triggers match. I agree, for people using the matching information we can put their triggers in the first 32 spots. 
That brings an other question who uses the matching information in general? I can say that in monojet we don't.
