### ISSUE TITLE
Jet ID 13 TeV 

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#265]
I was told that these changed recently.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID#Recommendations_for_13_TeV_data
@zdemirag, you will need to decide if you want to keep the old id as well and how to name the two.

**Comment by zdemirag** [comment]
I am aware of the changes. Also things regarding the v-tagging changed. I plan to implement it all for the 8_0_20 release as discussed.

**Comment by amarini** [comment]
ok. Thanks.
