### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#266]
Ntuples are indeed very big.
We need to make them smaller.

This is one of the last:

![](https://amarini.web.cern.ch/amarini/cms-private/Nero/NeroSize.png)

The average is 3k/event.

**Comment by amarini** [comment]
In order (reverse) per size :
*Br   12 :jetRefPt  : vector<float>                                =      38187 *
*Br  132 :genPdgId  : vector<int>                                  =      40684 *
*Br  152 :genIsoFrixione : vector<float>                           =      41788 *
*Br  153 :genParent : vector<int>                                  =      45042 *
*Br  151 :genIso    : vector<float>                                =      45204 *
*Br   80 :eleP4_smear : TClonesArray                               =      59544 *
*Br   52 :tauP4     : TClonesArray                                 =     106124 *
*Br   31 :jetpuppiP4 : TClonesArray                                =     158449 *
*Br  131 :genjetP4  : TClonesArray                                 =     193334 *
*Br    9 :jetP4     : TClonesArray                                 =     203253 *
*Br   88 :metSyst   : TClonesArray                                 =     288359 *
*Br  150 :pdfRwgt   : vector<float>                                =     458460 *
*Br  130 :genP4     : TClonesArray                                 =     911407 *

**Comment by amarini** [comment]
Action item 1. Put pdf and scale reweight as flags. I'm currently not using them, and I don't know who is.

**Comment by amarini** [comment]
Action item 2: MET uncertainties. 
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/interface/BareMet.hpp#L44
from miniAOD I'm using: JesUp= 0 , JesDown, JerUp, JerDown, UnclusterUp, UnclusterDown
photons, electrons and taus do not make any sense to be saved (will be the energy scale calibration) muon I don't know.
In principle, I'll try to reimplement the shift offline so I'll strictly need only Uncluster, but I would like to keep Jes and Jer for a little longer.

**Comment by amarini** [comment]
Action item 3. We are saving a lot of gen information. That will need to be reviewed.

**Comment by amarini** [comment]
Question: 
TLorentzVector are very expensive for two reasons: 1. double (partially covered by the compress) 2. the fact that they are saved internally as PxPyPzE that is not the best for the compression algorithms.
I tested it on the genjetP4: changing the TClonesArray -> vector<float> Pt, Eta,Phi,M
makes the size : 1.79M -> 1.33M (-34%) 
Since this would be a big change, I'm not implementing it unless there is general consensus.

**Comment by drkovalskyi** [comment]
Why not using float?

**Comment by amarini** [comment]
I would like to. Now they are stored as TLorentzVector, that handles them has double, i.e.  it saves 4 double per TLorentzVector: Px Py Pz E. We already compress the first three to float precision, zeroing the rest (that is random since miniaod has float precision), while we keep double on E to preserve the value of the mass. 
If we want to change to float, this means to restyle the TLorentzVector with 4 vector of floats. Now it is a good moment to do it, beacuse it is quite moment, but means that the macros that uses it needs to be updated, and this needs to be discussed.
Moreover, one needs to consider that half of our branches are TLorentzVector, so this would have a ~20% impact on the size.

**Comment by amarini** [comment]
#267
