### ISSUE TITLE
FatJets JEC

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#274]
Hi @zdemirag @sidnarayanan,
is there any reason why in the NeroFatJets we are using these sets of JEC:

https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroFatJets.cpp#L29-L36

In particular, old, and missing L1 ? 

I'll try to make them configurable.

Andrea

**Comment by zdemirag** [comment]
Hi Andrea,

L1 correction is not recommended for the mass quantities (which is what we are using the text files) The fat jets themselves are getting all L1,L2-L3 corrections.
We should make the text files configurable, I agree.

Zeynep
