### ISSUE TITLE
Content Review

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#301]
[**NeroFatJets**]

These are not readed (setBranch address) at the moment.
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareFatJets.cpp#L110-L114

Is this guy filled or used ? https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareFatJets.cpp#L142 

[**NeroJets**]
Is somebody using the legacy btag discriminator:
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareJets.cpp#L104

The PUId ? 
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareJets.cpp#L106

Q no PU?
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareJets.cpp#L127

[**NeroLeptons**]
This should go in the default P4
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareLeptons.cpp#L98
Anyhow now is not indexed as the other collection
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroLeptons.cpp#L256-L265

[**NeroMet**]
This should be out of the IsExtended part. I'm using only MetP4 and MetSyst shifts. 
I guess that here there are repetitions like pfMet_e3p0 and metNoHF.
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroMet.cpp#L101-L147

[**NeroMonteCarlo**]
Is somebody using PDF and Scale information (not reweights) 
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareMonteCarlo.cpp#L73-L80

Frixione Isolation?
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareMonteCarlo.cpp#L91

[**NeroPhotons**]
This should go in the default. (We save anyhow an extra object which is the refP4, eventually align names)
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BarePhotons.cpp#L123

**Comment by zdemirag** [comment]
I can update the fatjet / jet / met side.
I don't particularly have a preference with the rest (i.e. smeared electrons / photons or MC)

**Comment by amarini** [comment]
I will do leptons, photons and mc.
