### ISSUE TITLE
GenMET as calculated from the list of final state particles

### ISSUE THREAD

**Issue by yiiyama** [MiT-HEP/NeroProducer#34]
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroMonteCarlo.cpp#L74

The logic has to be inverted to pick up neutrinos and neutralinos (1000022, 1000023, 1000039, or just use charge == 0 && pdgId > 100000?)

**Comment by yiiyama** [comment]
Actually this genmet variable is not used anywhere.

**Comment by amarini** [comment]
Since we are using an acceptance (eta-restriction), genmet should be the opposite of what we observe (not neutrinos), and not the sum of what we don't observe (neutrinos and neutralinos) ...
Nevertheless it is not used, so I will comment it out for clarity.
