### ISSUE TITLE
FatJets

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#44]
- subjects in Fatjets.
- should be two for each fatjets that has subjects:
- root://eoscms///store/user/amarini/Nero/v1.0/RunIISpring15DR74/Asympt50ns_MCRUN2_74_V9A-v2/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/NeroNtuples_2.root
- I have 1304 fatjets, all with subjects and 1855 ak8_subjets.

am I wrong ?

(intersted in the argument @jsalfeld )

**Comment by zdemirag** [comment]
I am not sure if it got changed, but when doing the sync I was using the event dumper and 
I got 2 subjects for each fat jet. I didn’t check this event content regularly.

https://twiki.cern.ch/twiki/pub/CMS/DMS13TeVSynch/ADD_MIT.txt <https://twiki.cern.ch/twiki/pub/CMS/DMS13TeVSynch/ADD_MIT.txt>
https://twiki.cern.ch/twiki/pub/CMS/DMS13TeVSynch/TTBar_MIT.txt <https://twiki.cern.ch/twiki/pub/CMS/DMS13TeVSynch/TTBar_MIT.txt> (example 2nd event)

Maybe something changed between releases.
If you want you can assign it to me, I can take a look.

Zeynep

**Comment by amarini** [comment]
ok, can you have a look ? 
maybe we can save a map of pointers or try to find a better way to store this informations.

**Comment by zdemirag** [comment]
ok sure, can change it into a map.

**Comment by zdemirag** [comment]
@sidnarayanan will you add fat jet variables into nero?

**Comment by yiiyama** [comment]
@zdemirag He just did last night. #130
