### ISSUE TITLE
Post Nutples Skimmer

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#47]
May be useful to write a script that parse and skim ntuples, accordingly to a json file or to some cut.
- it should save the all tree completely 
- it should save a skimmed version of the events tree
- eventually should also be capable of dropping branches.

**Comment by zdemirag** [comment]
Here is an example for monojet (it also does some analysis specific removal)
https://github.com/MiT-HEP/MonoX/blob/master/monojet/slimmer/monojet.C
