### ISSUE TITLE
Histogram projection

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#53]
save histogram projection of the all tree: ( make it easier and faster access ) from MiniAOD ntuplizer.
* hDTotalMCWeight
* hDEvents
* hDPileup 

Compatibility with Bambu (?)

**Comment by amarini** [comment]
@zdemirag , @drkovalskyi  these are the histogram that we will need to save for projection purposes.

**Comment by drkovalskyi** [comment]
Is hDEvents just total number of events? What is hDPileup? What is the x-axis or they are just one 1-bin histograms?

**Comment by amarini** [comment]
Yes, I think that for for book-keeping we may store it anyway. they are just 1bin histograms (TH1D because the F precision is not enough for this purposes, at least in the sumW), except for pu, that stores the puTrueInt, (needed for the proper puReweight, if we are going to have it some day).

And these are the size of the different stuff in data (MET) and MC (DY)
https://amarini.web.cern.ch/amarini/Nero_v1-0-3/?match=%2FNeroSize_DY[^_]|NeroSize_MET%2F&depth=1
