### ISSUE TITLE
PF-component MET branch names?

### ISSUE THREAD

**Issue by yiiyama** [MiT-HEP/NeroProducer#67]
Just noticed that the branch names for the phi of PF CH/NH/Ph MET have changed:
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareMet.cpp

How was this supposed to work? At least setBranchAddresses and defineBranches are inconsistent, and I think it makes it extremely difficult (and possibly unreliable) to read branches when two with identical names exist, even if the leaf names are different..

**Comment by amarini** [comment]
@zdemirag is going to change MET branch names and put them into 4-vectors, for consistensy with all the other 4vectors. 
She is going to add the met up to eta 3.0 too.

In this case you can access to branches with dot: branch.leaf: 
eg, t->Draw("metNoMu.Phi")

**Comment by zdemirag** [comment]
indeed, all will be turned into 4 vectors, with the addition of met up to 3.0 in eta.
should be done later today.
